export const projects = [
  {
    title: 'Zoom Clone',
    description: 'Deployed a Zoom clone on a Heroku server in Node.js run-time environment with server-side code written using Express frameworks and sending & receiving connection requests through web sockets.',
    image: '/images/zoom.png',
    tags: ['Node.js', 'socket.io', 'Heroku'],
    source: 'https://github.com/anishyadav893/zoom-clone-nodejs',
    id: 0,
  },{
    title: 'Messaging App',
    description: 'Deployed a messaging application that uses WebSockets and ChatEngine for real-time communication between users, and provides the functionality of uploading images and creating multiple rooms.',
    image: '/images/messaging.jpg',
    tags: ['React', 'WebSockets', 'ChatEngine'],
    source: 'https://github.com/anishyadav893/messaging-app-reactjs',
    id: 1,
  },{
    title: 'Workout Tracker',
    description: 'Developed a workout information logging application with React on the frontend, nodemon server for setting up JavaScript environment in Express and the database is on MongoDB Atlas.',
    image: '/images/workout.jpg',
    tags: ['MongoDB', 'Express', 'Node.js', 'React'],
    source: 'https://github.com/anishyadav893/workout-tracker-mern',
    id: 2,
  },{
    title: 'Reddit Clone',
    description: 'Developed a Reddit clone written in Python. The app uses SQLAlchemy for storing data and the Flask framework for setting up the API routes and communicating between the frontend and backend.',
    image: '/images/reddit.jpg',
    tags: ['Python', 'Flask', 'SQLAlchemy', 'Bootstrap'],
    source: 'https://github.com/anishyadav893/reddit-clone-flask',
    id: 3,
  },{
    title: 'eCommerce Website',
    description: 'Implemented an eCommerce website with account login functionality and payment method. The application is developed using Django, with JavaScript for UI and Jinja templating for rendering webpages.',
    image: '/images/shopping.jpg',
    tags: ['Python', 'Django', 'Jinja', 'JavaScript'],
    source: 'https://github.com/anishyadav893/eCommerce-website-django',
    id: 4,
  },{
    title: 'Facebook Clone',
    description: 'Developed a Facebook clone built with React that uses context API to make real-time data available for use, Flexbox for responsiveness, react-flip-move for animations and validates users via Google authentication.',
    image: '/images/fb.png',
    tags: ['React', 'Firebase', 'Context API'],
    source: 'https://github.com/anishyadav893/facebook-clone-reactjs',
    id: 5,
  },{
    title: 'Python Web App',
    description: 'Developed a full web stack application using only Python. The backend routes are defined using the Flask framework and Anvil is used for designing the UI and hosting the web application where you can browse jobs and save them.',
    image: '/images/python.jpeg',
    tags: ['Python', 'Flask', 'Anvil'],
    source: 'https://github.com/anishyadav893/frontend-backend-in-python',
    id: 6,
  },{
    title: 'Feedback Form',
    description: 'Created a feedback submission form using the Flask framework which adds a user\'s feedback to a PostgreSQL database and confirms the feedback submission of any given user via mailtrap.',
    image: '/images/feedback.png',
    tags: ['Python', 'Flask', 'Mailtrap', 'PostgreSQL'],
    source: 'https://github.com/anishyadav893/feedback-form-flask',
    id: 7,
  },{
    title: 'Weather Info App',
    description: 'Developed a weather application using Flask and external API calls which validates whether a city exists, then add that city to the database, and return the current weather details of that city.',
    image: '/images/weather.jpg',
    tags: ['APIs', 'Python', 'Flask', 'SQLAlchemy'],
    source: 'https://github.com/anishyadav893/weather-app-flask',
    id: 8,
  },{
    title: 'News Portal',
    description: 'A news portal application developed for an academic project. The page styling is done using CSS, on-click and button functionalities are provided using JavaScript, and server-side code is written in PHP.',
    image: '/images/news.jpg',
    tags: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    source: 'https://github.com/anishyadav893/news-portal-php',
    id: 9,
  },{
    title: 'Color Picker Game',
    description: 'A simple color changer game written in HTML, CSS & JavaScript with multiple difficulty levels and prompting to the user to click on the correct color corresponding to the RGB value on the top of the webpage.',
    image: '/images/color.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/anishyadav893/rgb-game',
    id: 10,
  },{
    title: 'To-Do App',
    description: 'A basic CRUD application written as a single webpage which lets the user create a personalized to-do list. The webpage is styled using CSS, and the user interaction part is handled using jQuery plugins.',
    image: '/images/to-do.jpg',
    tags: ['HTML', 'CSS', 'jQuery'],
    source: 'https://github.com/anishyadav893/todo-app',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Data Analyst Intern at Growdiesel Ventures', },
  { year: 2018, text: 'Obtained Bachelor\'s from IIT Bombay', },
  { year: 2018, text: 'Data Analyst at Proliferator Advisory', },
  { year: 2019, text: 'Came to USA, joined Santa Clara University', },
  { year: 2020, text: 'Data Analyst Intern at Atollogy', },
  { year: 2021, text: 'Obtained Master\'s from Santa Clara University', },
];